### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by joeblew99** [justinfagnani/stampino#2]
this with Polymer expressions looks super useful for me, and i suspect many.

I am building large apps with polymer and a templating with expression layer helps:
- Great for code gen 
- Have lots of forms linked back to the data model. JSON Schema is a perfect example. I use goa bt (https://goa.design/), which i use to code gen al my JS right now. But with your lib it will allow run time data models too, not just design time ones.

anyway just wanted to say this is very useful and will propel Polymer i feel.

If you need help in anyway feel free to shout.

**Comment by justinfagnani** [comment]
Thanks @joeblew99! I haven't looked at this repo much in the last 4 years obviously, but I appreciate it :)
