### ISSUE TITLE
Regexp breaks Safari

### ISSUE THREAD

**Issue by bennypowers** [justinfagnani/stampino#28]
https://github.com/justinfagnani/stampino/blob/9a1e5b258e761af4041ce0b4bb76c7558e1c1693/src/stampino.ts#L385-L389
This regexp breaks on Safari

> SyntaxError: Invalid regular expression: invalid group specifier name —

**Comment by bennypowers** [comment]
Lookbehinds landed in safari tp today

**Comment by justinfagnani** [comment]
I wrote this in #29:

> I took another crack at this and I can't figure out how to match strings like `\{{ {{ x }}` correctly without either negative lookbehind or writing a little parser in JS. Considering that Safari has shipped lookbehinds for a year, and that Stampino just isn't used that much, we can just close this. If someone needs to support older Safari we could add a small parser then.
