### ISSUE TITLE
connectedCallback() is not getting triggered when using inside nested customElements

### ISSUE THREAD

**Issue by dsadhanala** [justinfagnani/stampino#3]
Thanks for the awesome template system, really helpful.

I have been working on a web components and want to use stampino for rending customElements markup from <template> element created in JS. While implementing of re-rendering customElement when attribute changed, I noticed it works well for elements that directly added in HTML, however when it is used as nested element inside template of another customElement connectedCallback() never gets called.

FYI, I'm using ES6 literals to create template element in JS. Here is a very basic example for your reference.
https://plnkr.co/edit/3hEM8NOmUZ6h0zNJVwG0?p=preview

Is this supported at all? any help would be greatly appreciated.

**Comment by lastmjs** [comment]
I think I've got this same issue just with custom elements in general. The `connectedCallback` is never firing when I add the element within an element, but when added to the body the `connectedCallback` does fire.

**Comment by lastmjs** [comment]
Actually, my problem had to do with shadow DOM. I put an element (element 2) within an element (element 1) without declaring a shadowRoot with a slot, and when I appended an element to element 2, the connectedCallback was not called. I think it's because element 2 was no longer part of the document

**Comment by dsadhanala** [comment]
FYI, I have tried same example with `lit-html` and it's actually working pretty good. However I'm not sure how stable and performant it is compared to `stampino with incremental-dom`.

Here is the example for reference:
https://plnkr.co/edit/v9kEY2q1JlrxJ6I4iAvr?p=preview

**Comment by justinfagnani** [comment]
Old issue is old, but if this was a problem it's hopefully fixed with the upcoming port to lit-html 2.0 that I just merged.
