### ISSUE TITLE
 Multiple interpolations in text node break content order

### ISSUE THREAD

**Issue by malte-christian** [justinfagnani/stampino#30]
Rendering `<p>{{item}} - {{item}}</p>` with `item="abc"` results in `<p>abcabc - </p>` instead of `<p>abc - abc</p>`. 
Not sure if related to https://github.com/justinfagnani/stampino/issues/27.

**Comment by bennypowers** [comment]
while we wait for PR review you can workaround by wrapping child interpolations in `<span>` elements

**Comment by justinfagnani** [comment]
Fixed in https://github.com/justinfagnani/stampino/commit/73e6cdb67fc1e185b435b172b40c896150dbd7d7
