### ISSUE TITLE
Uncaught SyntaxError: import not found: _Σ

### ISSUE THREAD

**Issue by bennypowers** [justinfagnani/stampino#32]
```bash
git clone https://github.com/superchris/apollo-elements-test
cd apollo-elements-test 
npm ci
npm run start:serve
```

`src/main.ts` imports `@apollo-elements/components`, which imports `stampino`.

> Uncaught SyntaxError: import not found: _Σ stampino.ts:7:8

See https://github.com/apollo-elements/apollo-elements/issues/218#issuecomment-1002908295

**Comment by justinfagnani** [comment]
Fixed in 0.7.0
