### ISSUE TITLE
Support RDFa templates

### ISSUE THREAD

**Issue by kenwenzel** [justinfagnani/stampino#34]
I am trying to modify stampino to support [RDFa](https://www.w3.org/TR/rdfa-core/)-based HTML templates of the following form:

```html
    <p about="?s" typeof="rdfs:Resource" prefix="rdfs: http://www.w3.org/2000/01/rdf-schema#">
      <span property="rdfs:label" content="?label"></span>
    </p>
```

Those templates allow to use variables (prefixed with '?') that are filled by a corresponding (automatically generated) [SPARQL ](http://www.w3.org/TR/sparql11-overview/) query:

```sparql
    select ?s ?label where {
        ?s a <http://www.w3.org/2000/01/rdf-schema#Resource> .
        ?s <http://www.w3.org/2000/01/rdf-schema#label> ?label .
    }
```
The result of such a query looks like:

```json
{
  "head": { "vars": [ "s" , "label" ] } ,
  "results": { 
    "bindings": [
      {
        "s": { "type": "uri" , "value": "http://example.org/someThing" } ,
        "label": { "type": "literal" , "value": "Thing 1" }
      },
      {
        "s": { "type": "uri" , "value": "http://example.org/someOtherThing" } ,
        "label": { "type": "literal" , "value": "Thing 2" }
      }
    ]
  }
}
```
Now the point is that I need to repeat the elements in the template for each binding in the SPARQL result.
I think this is easily achievable by reusing the logic from stampinos `<template type="repeat">`.

Now my question is if it is possible to combine this repetition with additional bindings like `<p @click="{{ handleClick }}">` on the same element.
Do you have any advice for me?

**Comment by kenwenzel** [comment]
Sorry for asking again. Do you have any suggestions for me or is it better to directly start a discussion within lit?

**Comment by kenwenzel** [comment]
I've found a first solution that is based on the same logic as the repeat handler:
https://github.com/kenwenzel/stampino/blob/ae244d7af41bcc89118dd7e7c20010f901998957/src/lit-rdfa.ts#L174

**Comment by justinfagnani** [comment]
I don't really understand the question here. Is this still an issue?

**Comment by kenwenzel** [comment]
The issue can be closed. I've fixed it with the above mentioned solution.
Thank you.
